name: Create tag
on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          DATE=$(date -u +"%Y%m%d")
          TAG_NAME="${DATE}-${{ github.run_number }}"
          git tag -a "${TAG_NAME}" -m "Deployed to pre-production environment by GitHub Actions"
          git push origin "${TAG_NAME}"
